version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: flexi-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: flexi
    ports:
      - "5432:5432"
    volumes:
      - flexi-data:/var/lib/postgresql/data

volumes:
  flexi-data:
